// All 105+ Tools Data for DocOpsCloud
export const ALL_TOOLS = {
  pdf: {
    name: "PDF Tools",
    icon: "📄",
    count: 35,
    tools: [
      { id: "pdf-merge", name: "Merge PDFs", description: "Combine multiple PDF files into one", icon: "🔗" },
      { id: "pdf-split", name: "Split PDF", description: "Extract pages or split into multiple files", icon: "✂️" },
      { id: "pdf-compress", name: "Compress PDF", description: "Reduce PDF file size up to 90%", icon: "🗜️" },
      { id: "pdf-to-images", name: "PDF to Images", description: "Convert pages to PNG/JPEG", icon: "🖼️" },
      { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable DOCX", icon: "📝" },
      { id: "pdf-to-excel", name: "PDF to Excel", description: "Extract tables to XLSX", icon: "📊" },
      { id: "pdf-to-ppt", name: "PDF to PowerPoint", description: "Convert to PPTX presentation", icon: "📊" },
      { id: "pdf-watermark", name: "Add Watermark", description: "Add text or image watermarks", icon: "🏷️" },
      { id: "pdf-rotate", name: "Rotate Pages", description: "Rotate PDF pages by degrees", icon: "🔄" },
      { id: "pdf-page-numbers", name: "Add Page Numbers", description: "Number your PDF pages", icon: "🔢" },
      { id: "pdf-extract-text", name: "Extract Text", description: "Get all text from PDF", icon: "📝" },
      { id: "pdf-extract-images", name: "Extract Images", description: "Save all images from PDF", icon: "🖼️" },
      { id: "pdf-remove-pages", name: "Remove Pages", description: "Delete specific pages", icon: "🗑️" },
      { id: "pdf-reorder", name: "Reorder Pages", description: "Rearrange page order", icon: "🔀" },
      { id: "pdf-password-protect", name: "Password Protect", description: "Add password security", icon: "🔒" },
      { id: "pdf-remove-password", name: "Remove Password", description: "Unlock protected PDFs", icon: "🔓" },
      { id: "pdf-metadata", name: "Edit Metadata", description: "Change PDF properties", icon: "ℹ️" },
      { id: "pdf-ocr", name: "OCR Scan", description: "Make scanned PDFs searchable", icon: "🔍" },
      { id: "pdf-sign", name: "Digital Signature", description: "Sign documents electronically", icon: "✍️" },
      { id: "pdf-redact", name: "Redact Content", description: "Permanently remove sensitive info", icon: "⬛" },
      { id: "pdf-flatten", name: "Flatten PDF", description: "Convert forms to static content", icon: "📄" },
      { id: "pdf-linearize", name: "Linearize PDF", description: "Optimize for fast web view", icon: "⚡" },
      { id: "pdf-repair", name: "Repair PDF", description: "Fix corrupted PDF files", icon: "🔧" },
      { id: "pdf-compare", name: "Compare PDFs", description: "Find differences between files", icon: "🔍" },
      { id: "pdf-header-footer", name: "Add Header/Footer", description: "Insert headers and footers", icon: "📋" },
      { id: "pdf-background", name: "Add Background", description: "Insert background image", icon: "🎨" },
      { id: "pdf-bookmarks", name: "Add Bookmarks", description: "Create PDF navigation", icon: "🔖" },
      { id: "pdf-crop", name: "Crop Pages", description: "Trim page margins", icon: "✂️" },
      { id: "pdf-grayscale", name: "Convert to Grayscale", description: "Remove colors", icon: "⚫" },
      { id: "pdf-optimize-web", name: "Optimize for Web", description: "Reduce size for online use", icon: "🌐" },
      { id: "pdf-form-fill", name: "Fill Forms", description: "Auto-fill PDF forms", icon: "📝" },
      { id: "pdf-convert-pdfa", name: "Convert to PDF/A", description: "Create archival PDFs", icon: "📦" },
      { id: "pdf-portfolio", name: "Create Portfolio", description: "Combine different file types", icon: "📁" },
      { id: "pdf-reduce-size", name: "Reduce File Size", description: "Advanced compression", icon: "📉" },
      { id: "pdf-print-ready", name: "Print Optimization", description: "Optimize for printing", icon: "🖨️" },
    ]
  },
  word: {
    name: "Word Tools",
    icon: "📝",
    count: 25,
    tools: [
      { id: "word-to-pdf", name: "Word to PDF", description: "Convert DOCX to PDF", icon: "📄" },
      { id: "word-to-html", name: "Word to HTML", description: "Convert to clean HTML", icon: "🌐" },
      { id: "word-to-markdown", name: "Word to Markdown", description: "Convert to MD format", icon: "📋" },
      { id: "word-to-txt", name: "Word to Text", description: "Extract plain text", icon: "📝" },
      { id: "word-to-images", name: "Word to Images", description: "Convert pages to images", icon: "🖼️" },
      { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable DOCX", icon: "📝" },
      { id: "word-merge", name: "Merge Documents", description: "Combine multiple Word files", icon: "🔗" },
      { id: "word-split", name: "Split Document", description: "Divide into multiple files", icon: "✂️" },
      { id: "word-compress", name: "Compress Word", description: "Reduce DOCX file size", icon: "🗜️" },
      { id: "word-watermark", name: "Add Watermark", description: "Insert text/image watermark", icon: "🏷️" },
      { id: "word-metadata", name: "Edit Metadata", description: "Modify document properties", icon: "ℹ️" },
      { id: "word-password", name: "Password Protect", description: "Secure your documents", icon: "🔒" },
      { id: "word-remove-password", name: "Remove Password", description: "Unlock protected files", icon: "🔓" },
      { id: "word-find-replace", name: "Find & Replace", description: "Batch text replacement", icon: "🔍" },
      { id: "word-compare", name: "Compare Documents", description: "Track changes between versions", icon: "🔍" },
      { id: "word-page-count", name: "Page Counter", description: "Count pages and words", icon: "🔢" },
      { id: "word-remove-comments", name: "Remove Comments", description: "Clean up tracked changes", icon: "🗑️" },
      { id: "word-extract-images", name: "Extract Images", description: "Save all embedded images", icon: "🖼️" },
      { id: "word-format-clean", name: "Clean Formatting", description: "Remove formatting issues", icon: "🧹" },
      { id: "word-sign", name: "Digital Signature", description: "Sign documents", icon: "✍️" },
      { id: "word-toc", name: "Generate TOC", description: "Create table of contents", icon: "📑" },
      { id: "word-mail-merge", name: "Mail Merge", description: "Batch document generation", icon: "📧" },
      { id: "word-template", name: "Apply Template", description: "Use predefined styles", icon: "🎨" },
      { id: "word-accessibility", name: "Accessibility Check", description: "Ensure document accessibility", icon: "♿" },
      { id: "word-translate", name: "Translate Document", description: "AI-powered translation", icon: "🌍" },
    ]
  },
  excel: {
    name: "Excel & CSV Tools",
    icon: "📊",
    count: 30,
    tools: [
      { id: "excel-to-csv", name: "Excel to CSV", description: "Convert XLSX to CSV", icon: "📉" },
      { id: "csv-to-excel", name: "CSV to Excel", description: "Convert CSV to XLSX", icon: "📈" },
      { id: "excel-to-pdf", name: "Excel to PDF", description: "Convert spreadsheets to PDF", icon: "📄" },
      { id: "excel-to-json", name: "Excel to JSON", description: "Export as JSON data", icon: "{ }" },
      { id: "excel-to-xml", name: "Excel to XML", description: "Convert to XML format", icon: "📄" },
      { id: "excel-merge", name: "Merge Spreadsheets", description: "Combine multiple files", icon: "🔗" },
      { id: "excel-split", name: "Split Sheets", description: "Export each sheet separately", icon: "✂️" },
      { id: "excel-compress", name: "Compress Excel", description: "Reduce file size", icon: "🗜️" },
      { id: "csv-clean", name: "Clean CSV Data", description: "Remove duplicates & errors", icon: "🧹" },
      { id: "excel-password", name: "Password Protect", description: "Secure your spreadsheets", icon: "🔒" },
      { id: "excel-remove-password", name: "Remove Password", description: "Unlock protected files", icon: "🔓" },
      { id: "excel-formula-calculate", name: "Calculate Formulas", description: "Evaluate all formulas", icon: "🔢" },
      { id: "excel-chart-extract", name: "Extract Charts", description: "Save charts as images", icon: "📊" },
      { id: "excel-pivot-table", name: "Create Pivot Table", description: "Generate data summaries", icon: "📊" },
      { id: "excel-data-validate", name: "Data Validation", description: "Check data quality", icon: "✅" },
      { id: "excel-remove-duplicates", name: "Remove Duplicates", description: "Clean duplicate rows", icon: "🗑️" },
      { id: "excel-sort-data", name: "Sort Data", description: "Auto-sort spreadsheets", icon: "🔀" },
      { id: "excel-filter-data", name: "Filter Data", description: "Apply advanced filters", icon: "🔍" },
      { id: "excel-transpose", name: "Transpose Data", description: "Swap rows and columns", icon: "🔄" },
      { id: "excel-concatenate", name: "Concatenate Columns", description: "Merge column data", icon: "🔗" },
      { id: "excel-split-columns", name: "Split Columns", description: "Divide column data", icon: "✂️" },
      { id: "csv-delimiter-change", name: "Change Delimiter", description: "Convert CSV separators", icon: "📋" },
      { id: "excel-statistics", name: "Statistical Analysis", description: "Generate statistics", icon: "📊" },
      { id: "excel-find-replace", name: "Find & Replace", description: "Batch text replacement", icon: "🔍" },
      { id: "excel-format-numbers", name: "Format Numbers", description: "Apply number formatting", icon: "🔢" },
      { id: "excel-date-format", name: "Format Dates", description: "Standardize date formats", icon: "📅" },
      { id: "excel-currency-convert", name: "Currency Conversion", description: "Convert between currencies", icon: "💱" },
      { id: "excel-vlookup", name: "VLOOKUP Helper", description: "Automated lookups", icon: "🔍" },
      { id: "excel-macro-remove", name: "Remove Macros", description: "Clean VBA code", icon: "🧹" },
      { id: "excel-template", name: "Apply Template", description: "Use predefined formats", icon: "🎨" },
    ]
  },
  utility: {
    name: "Utility & Analysis Tools",
    icon: "🔧",
    count: 25,
    tools: [
      { id: "text-analyzer", name: "Text Analyzer", description: "Word count, readability score, sentiment analysis", icon: "📊" },
      { id: "hash-generator", name: "Hash Generator", description: "Generate MD5, SHA-1, SHA-256 checksums", icon: "🔐" },
      { id: "file-compare", name: "File Comparator", description: "Compare two files and find differences", icon: "🔍" },
      { id: "qr-generator", name: "QR Code Generator", description: "Create QR codes from text or URLs", icon: "📱" },
      { id: "barcode-generator", name: "Barcode Generator", description: "Generate various barcode formats", icon: "📊" },
      { id: "json-formatter", name: "JSON Formatter", description: "Format and validate JSON data", icon: "{ }" },
      { id: "xml-formatter", name: "XML Formatter", description: "Format and validate XML data", icon: "📄" },
      { id: "base64-encode", name: "Base64 Encoder", description: "Encode/decode Base64 strings", icon: "🔢" },
      { id: "url-encoder", name: "URL Encoder", description: "Encode/decode URL strings", icon: "🔗" },
      { id: "markdown-preview", name: "Markdown Preview", description: "Render markdown to HTML preview", icon: "📝" },
      { id: "lorem-generator", name: "Lorem Ipsum Generator", description: "Generate placeholder text", icon: "📜" },
      { id: "password-generator", name: "Password Generator", description: "Create strong random passwords", icon: "🔑" },
      { id: "uuid-generator", name: "UUID Generator", description: "Generate unique identifiers", icon: "🆔" },
      { id: "color-converter", name: "Color Converter", description: "Convert between HEX, RGB, HSL", icon: "🎨" },
      { id: "timestamp-converter", name: "Timestamp Converter", description: "Unix timestamp to date conversion", icon: "⏰" },
      { id: "regex-tester", name: "Regex Tester", description: "Test regular expressions", icon: "🔤" },
      { id: "diff-checker", name: "Diff Checker", description: "Compare text and find differences", icon: "📊" },
      { id: "word-frequency", name: "Word Frequency", description: "Analyze word usage patterns", icon: "📈" },
      { id: "character-counter", name: "Character Counter", description: "Count characters, words, sentences", icon: "🔢" },
      { id: "case-converter", name: "Case Converter", description: "Convert text case styles", icon: "Aa" },
      { id: "duplicate-finder", name: "Duplicate Finder", description: "Find duplicate lines in text", icon: "🔍" },
      { id: "line-sorter", name: "Line Sorter", description: "Sort lines alphabetically or numerically", icon: "🔀" },
      { id: "text-reverser", name: "Text Reverser", description: "Reverse text or words", icon: "↩️" },
      { id: "slug-generator", name: "Slug Generator", description: "Create URL-friendly slugs", icon: "🔗" },
      { id: "html-encoder", name: "HTML Encoder", description: "Encode/decode HTML entities", icon: "🌐" },
    ]
  },
  image: {
    name: "Image Tools",
    icon: "🖼️",
    count: 30,
    tools: [
      { id: "image-resize", name: "Resize Image", description: "Change dimensions precisely", icon: "📐" },
      { id: "image-compress", name: "Compress Image", description: "Reduce file size up to 80%", icon: "🗜️" },
      { id: "image-convert", name: "Convert Format", description: "Change image format", icon: "🔄" },
      { id: "image-crop", name: "Crop Image", description: "Trim to specific area", icon: "✂️" },
      { id: "image-rotate", name: "Rotate Image", description: "Rotate by any angle", icon: "🔄" },
      { id: "image-flip", name: "Flip Image", description: "Mirror horizontally/vertically", icon: "↔️" },
      { id: "image-watermark", name: "Add Watermark", description: "Protect with watermark", icon: "🏷️" },
      { id: "image-filter", name: "Apply Filters", description: "Grayscale, sepia, vintage", icon: "🎨" },
      { id: "image-blur", name: "Blur Image", description: "Apply blur effect", icon: "💫" },
      { id: "image-sharpen", name: "Sharpen Image", description: "Enhance sharpness", icon: "✨" },
      { id: "image-brightness", name: "Adjust Brightness", description: "Make lighter or darker", icon: "☀️" },
      { id: "image-contrast", name: "Adjust Contrast", description: "Enhance color contrast", icon: "🌗" },
      { id: "image-saturation", name: "Adjust Saturation", description: "Change color intensity", icon: "🎨" },
      { id: "image-grayscale", name: "Convert to Grayscale", description: "Remove all colors", icon: "⚫" },
      { id: "image-sepia", name: "Sepia Tone", description: "Vintage photo effect", icon: "📷" },
      { id: "image-optimize", name: "Optimize for Web", description: "Perfect for websites", icon: "🌐" },
      { id: "image-thumbnail", name: "Create Thumbnail", description: "Generate small preview", icon: "🖼️" },
      { id: "image-border", name: "Add Border", description: "Frame your images", icon: "🖼️" },
      { id: "image-background-remove", name: "Remove Background", description: "AI background removal", icon: "🎭" },
      { id: "image-upscale", name: "Upscale Image", description: "AI image enhancement", icon: "⬆️" },
      { id: "image-denoise", name: "Remove Noise", description: "Clean up grainy images", icon: "🧹" },
      { id: "image-color-picker", name: "Color Picker", description: "Extract color palette", icon: "🎨" },
      { id: "image-merge", name: "Merge Images", description: "Combine multiple images", icon: "🔗" },
      { id: "image-collage", name: "Create Collage", description: "Make photo collages", icon: "🖼️" },
      { id: "image-metadata", name: "View EXIF Data", description: "See photo information", icon: "ℹ️" },
      { id: "image-metadata-remove", name: "Remove EXIF Data", description: "Strip metadata", icon: "🗑️" },
      { id: "image-format-webp", name: "Convert to WebP", description: "Modern web format", icon: "🌐" },
      { id: "image-format-avif", name: "Convert to AVIF", description: "Next-gen image format", icon: "✨" },
      { id: "image-batch", name: "Batch Processing", description: "Process multiple images", icon: "⚙️" },
      { id: "image-gif-maker", name: "Create GIF", description: "Make animated GIFs", icon: "🎬" },
    ]
  },
  video: {
    name: "Video Tools",
    icon: "🎬",
    count: 20,
    tools: [
      { id: "video-compress", name: "Compress Video", description: "Reduce video file size up to 80%", icon: "🗜️" },
      { id: "video-convert", name: "Convert Video", description: "Convert between MP4, WebM, AVI, MOV", icon: "🔄" },
      { id: "video-trim", name: "Trim Video", description: "Cut video to specific duration", icon: "✂️" },
      { id: "video-merge", name: "Merge Videos", description: "Combine multiple videos into one", icon: "🔗" },
      { id: "video-split", name: "Split Video", description: "Divide video into segments", icon: "📐" },
      { id: "video-rotate", name: "Rotate Video", description: "Rotate by 90, 180, or 270 degrees", icon: "🔄" },
      { id: "video-crop", name: "Crop Video", description: "Remove unwanted areas", icon: "✂️" },
      { id: "video-resize", name: "Resize Video", description: "Change video dimensions", icon: "📐" },
      { id: "video-to-gif", name: "Video to GIF", description: "Create animated GIFs from video", icon: "🎞️" },
      { id: "video-extract-audio", name: "Extract Audio", description: "Get audio track from video", icon: "🎵" },
      { id: "video-remove-audio", name: "Remove Audio", description: "Mute video track", icon: "🔇" },
      { id: "video-add-audio", name: "Add Audio", description: "Add background music or voiceover", icon: "🎶" },
      { id: "video-add-subtitles", name: "Add Subtitles", description: "Burn subtitles into video", icon: "💬" },
      { id: "video-extract-frames", name: "Extract Frames", description: "Get images from video", icon: "🖼️" },
      { id: "video-speed", name: "Change Speed", description: "Speed up or slow down video", icon: "⏩" },
      { id: "video-reverse", name: "Reverse Video", description: "Play video backwards", icon: "⏪" },
      { id: "video-watermark", name: "Add Watermark", description: "Overlay logo or text", icon: "🏷️" },
      { id: "video-thumbnail", name: "Generate Thumbnail", description: "Create video preview image", icon: "🖼️" },
      { id: "video-stabilize", name: "Stabilize Video", description: "Remove camera shake", icon: "📷" },
      { id: "video-metadata", name: "Edit Metadata", description: "Change video properties", icon: "ℹ️" },
    ]
  },
  audio: {
    name: "Audio Tools",
    icon: "🎵",
    count: 15,
    tools: [
      { id: "audio-convert", name: "Convert Audio", description: "Convert MP3, WAV, FLAC, OGG, AAC", icon: "🔄" },
      { id: "audio-compress", name: "Compress Audio", description: "Reduce audio file size", icon: "🗜️" },
      { id: "audio-trim", name: "Trim Audio", description: "Cut audio to specific duration", icon: "✂️" },
      { id: "audio-merge", name: "Merge Audio", description: "Combine multiple audio files", icon: "🔗" },
      { id: "audio-split", name: "Split Audio", description: "Divide audio into segments", icon: "📐" },
      { id: "audio-normalize", name: "Normalize Audio", description: "Adjust volume levels", icon: "📊" },
      { id: "audio-fade", name: "Add Fade", description: "Fade in/out effects", icon: "📈" },
      { id: "audio-remove-noise", name: "Remove Noise", description: "Clean up background noise", icon: "🔇" },
      { id: "audio-speed", name: "Change Speed", description: "Speed up or slow down", icon: "⏩" },
      { id: "audio-reverse", name: "Reverse Audio", description: "Play audio backwards", icon: "⏪" },
      { id: "audio-extract-vocals", name: "Extract Vocals", description: "Separate voice from music", icon: "🎤" },
      { id: "audio-remove-vocals", name: "Remove Vocals", description: "Create karaoke version", icon: "🎶" },
      { id: "audio-equalizer", name: "Equalizer", description: "Adjust frequency bands", icon: "🎛️" },
      { id: "audio-metadata", name: "Edit Metadata", description: "Change ID3 tags", icon: "ℹ️" },
      { id: "audio-waveform", name: "Generate Waveform", description: "Create visual waveform image", icon: "📊" },
    ]
  },
  archive: {
    name: "Archive & Compression",
    icon: "📦",
    count: 12,
    tools: [
      { id: "zip-create", name: "Create ZIP", description: "Compress files to ZIP archive", icon: "📦" },
      { id: "zip-extract", name: "Extract ZIP", description: "Unzip archive contents", icon: "📂" },
      { id: "rar-extract", name: "Extract RAR", description: "Unpack RAR archives", icon: "📂" },
      { id: "7z-create", name: "Create 7Z", description: "High compression 7-Zip archive", icon: "📦" },
      { id: "7z-extract", name: "Extract 7Z", description: "Unpack 7-Zip archives", icon: "📂" },
      { id: "tar-create", name: "Create TAR.GZ", description: "Unix-style archive", icon: "📦" },
      { id: "tar-extract", name: "Extract TAR.GZ", description: "Unpack tar archives", icon: "📂" },
      { id: "archive-password", name: "Password Protect", description: "Encrypt archive with password", icon: "🔒" },
      { id: "archive-split", name: "Split Archive", description: "Divide large archives", icon: "✂️" },
      { id: "archive-repair", name: "Repair Archive", description: "Fix corrupted archives", icon: "🔧" },
      { id: "archive-list", name: "List Contents", description: "View archive contents without extracting", icon: "📋" },
      { id: "archive-convert", name: "Convert Archive", description: "Change archive format", icon: "🔄" },
    ]
  }
}

export const TOOL_CATEGORIES = [
  { id: "pdf", ...ALL_TOOLS.pdf },
  { id: "word", ...ALL_TOOLS.word },
  { id: "excel", ...ALL_TOOLS.excel },
  { id: "image", ...ALL_TOOLS.image },
  { id: "video", ...ALL_TOOLS.video },
  { id: "audio", ...ALL_TOOLS.audio },
  { id: "archive", ...ALL_TOOLS.archive },
  { id: "utility", ...ALL_TOOLS.utility },
]

export const getTotalToolCount = () => {
  return Object.values(ALL_TOOLS).reduce((sum, category) => sum + category.count, 0)
}

export const getAllTools = () => {
  return Object.values(ALL_TOOLS).flatMap(category =>
    category.tools.map(tool => ({ ...tool, category: category.name }))
  )
}

export const getToolById = (id: string) => {
  return getAllTools().find((tool) => tool.id === id)
}

export const getAllToolsFlat = () => {
  const tools: Array<{ id: string; name: string; description: string; icon: string; category: string }> = []
  Object.entries(ALL_TOOLS).forEach(([categoryKey, category]) => {
    category.tools.forEach(tool => {
      tools.push({ ...tool, category: categoryKey })
    })
  })
  return tools
}
