// All 105+ Tools Data for DocOpsCloud
export const ALL_TOOLS = {
  pdf: {
    name: "PDF Tools",
    icon: "📄",
    count: 35,
    tools: [
      { id: "pdf-merge", name: "Merge PDFs", description: "Combine multiple PDF files into one", icon: "🔗" },
      { id: "pdf-split", name: "Split PDF", description: "Extract pages or split into multiple files", icon: "✂️" },
      { id: "pdf-compress", name: "Compress PDF", description: "Reduce PDF file size up to 90%", icon: "🗜️" },
      { id: "pdf-to-images", name: "PDF to Images", description: "Convert pages to PNG/JPEG", icon: "🖼️" },
      { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable DOCX", icon: "📝" },
      { id: "pdf-to-excel", name: "PDF to Excel", description: "Extract tables to XLSX", icon: "📊" },
      { id: "pdf-to-ppt", name: "PDF to PowerPoint", description: "Convert to PPTX presentation", icon: "📊" },
      { id: "pdf-watermark", name: "Add Watermark", description: "Add text or image watermarks", icon: "🏷️" },
      { id: "pdf-rotate", name: "Rotate Pages", description: "Rotate PDF pages by degrees", icon: "🔄" },
      { id: "pdf-page-numbers", name: "Add Page Numbers", description: "Number your PDF pages", icon: "🔢" },
      { id: "pdf-extract-text", name: "Extract Text", description: "Get all text from PDF", icon: "📝" },
      { id: "pdf-extract-images", name: "Extract Images", description: "Save all images from PDF", icon: "🖼️" },
      { id: "pdf-remove-pages", name: "Remove Pages", description: "Delete specific pages", icon: "🗑️" },
      { id: "pdf-reorder", name: "Reorder Pages", description: "Rearrange page order", icon: "🔀" },
      { id: "pdf-password-protect", name: "Password Protect", description: "Add password security", icon: "🔒" },
      { id: "pdf-remove-password", name: "Remove Password", description: "Unlock protected PDFs", icon: "🔓" },
      { id: "pdf-metadata", name: "Edit Metadata", description: "Change PDF properties", icon: "ℹ️" },
      { id: "pdf-ocr", name: "OCR Scan", description: "Make scanned PDFs searchable", icon: "🔍" },
      { id: "pdf-sign", name: "Digital Signature", description: "Sign documents electronically", icon: "✍️" },
      { id: "pdf-redact", name: "Redact Content", description: "Permanently remove sensitive info", icon: "⬛" },
      { id: "pdf-flatten", name: "Flatten PDF", description: "Convert forms to static content", icon: "📄" },
      { id: "pdf-linearize", name: "Linearize PDF", description: "Optimize for fast web view", icon: "⚡" },
      { id: "pdf-repair", name: "Repair PDF", description: "Fix corrupted PDF files", icon: "🔧" },
      { id: "pdf-compare", name: "Compare PDFs", description: "Find differences between files", icon: "🔍" },
      { id: "pdf-header-footer", name: "Add Header/Footer", description: "Insert headers and footers", icon: "📋" },
      { id: "pdf-background", name: "Add Background", description: "Insert background image", icon: "🎨" },
      { id: "pdf-bookmarks", name: "Add Bookmarks", description: "Create PDF navigation", icon: "🔖" },
      { id: "pdf-crop", name: "Crop Pages", description: "Trim page margins", icon: "✂️" },
      { id: "pdf-grayscale", name: "Convert to Grayscale", description: "Remove colors", icon: "⚫" },
      { id: "pdf-optimize-web", name: "Optimize for Web", description: "Reduce size for online use", icon: "🌐" },
      { id: "pdf-form-fill", name: "Fill Forms", description: "Auto-fill PDF forms", icon: "📝" },
      { id: "pdf-convert-pdfa", name: "Convert to PDF/A", description: "Create archival PDFs", icon: "📦" },
      { id: "pdf-portfolio", name: "Create Portfolio", description: "Combine different file types", icon: "📁" },
      { id: "pdf-reduce-size", name: "Reduce File Size", description: "Advanced compression", icon: "📉" },
      { id: "pdf-print-ready", name: "Print Optimization", description: "Optimize for printing", icon: "🖨️" },
    ]
  },
  word: {
    name: "Word Tools",
    icon: "📝",
    count: 25,
    tools: [
      { id: "word-to-pdf", name: "Word to PDF", description: "Convert DOCX to PDF", icon: "📄" },
      { id: "word-to-html", name: "Word to HTML", description: "Convert to clean HTML", icon: "🌐" },
      { id: "word-to-markdown", name: "Word to Markdown", description: "Convert to MD format", icon: "📋" },
      { id: "word-to-txt", name: "Word to Text", description: "Extract plain text", icon: "📝" },
      { id: "word-to-images", name: "Word to Images", description: "Convert pages to images", icon: "🖼️" },
      { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable DOCX", icon: "📝" },
      { id: "word-merge", name: "Merge Documents", description: "Combine multiple Word files", icon: "🔗" },
      { id: "word-split", name: "Split Document", description: "Divide into multiple files", icon: "✂️" },
      { id: "word-compress", name: "Compress Word", description: "Reduce DOCX file size", icon: "🗜️" },
      { id: "word-watermark", name: "Add Watermark", description: "Insert text/image watermark", icon: "🏷️" },
      { id: "word-metadata", name: "Edit Metadata", description: "Modify document properties", icon: "ℹ️" },
      { id: "word-password", name: "Password Protect", description: "Secure your documents", icon: "🔒" },
      { id: "word-remove-password", name: "Remove Password", description: "Unlock protected files", icon: "🔓" },
      { id: "word-find-replace", name: "Find & Replace", description: "Batch text replacement", icon: "🔍" },
      { id: "word-compare", name: "Compare Documents", description: "Track changes between versions", icon: "🔍" },
      { id: "word-page-count", name: "Page Counter", description: "Count pages and words", icon: "🔢" },
      { id: "word-remove-comments", name: "Remove Comments", description: "Clean up tracked changes", icon: "🗑️" },
      { id: "word-extract-images", name: "Extract Images", description: "Save all embedded images", icon: "🖼️" },
      { id: "word-format-clean", name: "Clean Formatting", description: "Remove formatting issues", icon: "🧹" },
      { id: "word-sign", name: "Digital Signature", description: "Sign documents", icon: "✍️" },
      { id: "word-toc", name: "Generate TOC", description: "Create table of contents", icon: "📑" },
      { id: "word-mail-merge", name: "Mail Merge", description: "Batch document generation", icon: "📧" },
      { id: "word-template", name: "Apply Template", description: "Use predefined styles", icon: "🎨" },
      { id: "word-accessibility", name: "Accessibility Check", description: "Ensure document accessibility", icon: "♿" },
      { id: "word-translate", name: "Translate Document", description: "AI-powered translation", icon: "🌍" },
    ]
  },
  excel: {
    name: "Excel & CSV Tools",
    icon: "📊",
    count: 30,
    tools: [
      { id: "excel-to-csv", name: "Excel to CSV", description: "Convert XLSX to CSV", icon: "📉" },
      { id: "csv-to-excel", name: "CSV to Excel", description: "Convert CSV to XLSX", icon: "📈" },
      { id: "excel-to-pdf", name: "Excel to PDF", description: "Convert spreadsheets to PDF", icon: "📄" },
      { id: "excel-to-json", name: "Excel to JSON", description: "Export as JSON data", icon: "{ }" },
      { id: "excel-to-xml", name: "Excel to XML", description: "Convert to XML format", icon: "📄" },
      { id: "excel-merge", name: "Merge Spreadsheets", description: "Combine multiple files", icon: "🔗" },
      { id: "excel-split", name: "Split Sheets", description: "Export each sheet separately", icon: "✂️" },
      { id: "excel-compress", name: "Compress Excel", description: "Reduce file size", icon: "🗜️" },
      { id: "csv-clean", name: "Clean CSV Data", description: "Remove duplicates & errors", icon: "🧹" },
      { id: "excel-password", name: "Password Protect", description: "Secure your spreadsheets", icon: "🔒" },
      { id: "excel-remove-password", name: "Remove Password", description: "Unlock protected files", icon: "🔓" },
      { id: "excel-formula-calculate", name: "Calculate Formulas", description: "Evaluate all formulas", icon: "🔢" },
      { id: "excel-chart-extract", name: "Extract Charts", description: "Save charts as images", icon: "📊" },
      { id: "excel-pivot-table", name: "Create Pivot Table", description: "Generate data summaries", icon: "📊" },
      { id: "excel-data-validate", name: "Data Validation", description: "Check data quality", icon: "✅" },
      { id: "excel-remove-duplicates", name: "Remove Duplicates", description: "Clean duplicate rows", icon: "🗑️" },
      { id: "excel-sort-data", name: "Sort Data", description: "Auto-sort spreadsheets", icon: "🔀" },
      { id: "excel-filter-data", name: "Filter Data", description: "Apply advanced filters", icon: "🔍" },
      { id: "excel-transpose", name: "Transpose Data", description: "Swap rows and columns", icon: "🔄" },
      { id: "excel-concatenate", name: "Concatenate Columns", description: "Merge column data", icon: "🔗" },
      { id: "excel-split-columns", name: "Split Columns", description: "Divide column data", icon: "✂️" },
      { id: "csv-delimiter-change", name: "Change Delimiter", description: "Convert CSV separators", icon: "📋" },
      { id: "excel-statistics", name: "Statistical Analysis", description: "Generate statistics", icon: "📊" },
      { id: "excel-find-replace", name: "Find & Replace", description: "Batch text replacement", icon: "🔍" },
      { id: "excel-format-numbers", name: "Format Numbers", description: "Apply number formatting", icon: "🔢" },
      { id: "excel-date-format", name: "Format Dates", description: "Standardize date formats", icon: "📅" },
      { id: "excel-currency-convert", name: "Currency Conversion", description: "Convert between currencies", icon: "💱" },
      { id: "excel-vlookup", name: "VLOOKUP Helper", description: "Automated lookups", icon: "🔍" },
      { id: "excel-macro-remove", name: "Remove Macros", description: "Clean VBA code", icon: "🧹" },
      { id: "excel-template", name: "Apply Template", description: "Use predefined formats", icon: "🎨" },
    ]
  },
  image: {
    name: "Image Tools",
    icon: "🖼️",
    count: 30,
    tools: [
      { id: "image-resize", name: "Resize Image", description: "Change dimensions precisely", icon: "📐" },
      { id: "image-compress", name: "Compress Image", description: "Reduce file size up to 80%", icon: "🗜️" },
      { id: "image-convert", name: "Convert Format", description: "Change image format", icon: "🔄" },
      { id: "image-crop", name: "Crop Image", description: "Trim to specific area", icon: "✂️" },
      { id: "image-rotate", name: "Rotate Image", description: "Rotate by any angle", icon: "🔄" },
      { id: "image-flip", name: "Flip Image", description: "Mirror horizontally/vertically", icon: "↔️" },
      { id: "image-watermark", name: "Add Watermark", description: "Protect with watermark", icon: "🏷️" },
      { id: "image-filter", name: "Apply Filters", description: "Grayscale, sepia, vintage", icon: "🎨" },
      { id: "image-blur", name: "Blur Image", description: "Apply blur effect", icon: "💫" },
      { id: "image-sharpen", name: "Sharpen Image", description: "Enhance sharpness", icon: "✨" },
      { id: "image-brightness", name: "Adjust Brightness", description: "Make lighter or darker", icon: "☀️" },
      { id: "image-contrast", name: "Adjust Contrast", description: "Enhance color contrast", icon: "🌗" },
      { id: "image-saturation", name: "Adjust Saturation", description: "Change color intensity", icon: "🎨" },
      { id: "image-grayscale", name: "Convert to Grayscale", description: "Remove all colors", icon: "⚫" },
      { id: "image-sepia", name: "Sepia Tone", description: "Vintage photo effect", icon: "📷" },
      { id: "image-optimize", name: "Optimize for Web", description: "Perfect for websites", icon: "🌐" },
      { id: "image-thumbnail", name: "Create Thumbnail", description: "Generate small preview", icon: "🖼️" },
      { id: "image-border", name: "Add Border", description: "Frame your images", icon: "🖼️" },
      { id: "image-background-remove", name: "Remove Background", description: "AI background removal", icon: "🎭" },
      { id: "image-upscale", name: "Upscale Image", description: "AI image enhancement", icon: "⬆️" },
      { id: "image-denoise", name: "Remove Noise", description: "Clean up grainy images", icon: "🧹" },
      { id: "image-color-picker", name: "Color Picker", description: "Extract color palette", icon: "🎨" },
      { id: "image-merge", name: "Merge Images", description: "Combine multiple images", icon: "🔗" },
      { id: "image-collage", name: "Create Collage", description: "Make photo collages", icon: "🖼️" },
      { id: "image-metadata", name: "View EXIF Data", description: "See photo information", icon: "ℹ️" },
      { id: "image-metadata-remove", name: "Remove EXIF Data", description: "Strip metadata", icon: "🗑️" },
      { id: "image-format-webp", name: "Convert to WebP", description: "Modern web format", icon: "🌐" },
      { id: "image-format-avif", name: "Convert to AVIF", description: "Next-gen image format", icon: "✨" },
      { id: "image-batch", name: "Batch Processing", description: "Process multiple images", icon: "⚙️" },
      { id: "image-gif-maker", name: "Create GIF", description: "Make animated GIFs", icon: "🎬" },
    ]
  }
}

export const TOOL_CATEGORIES = [
  { id: "pdf", ...ALL_TOOLS.pdf },
  { id: "word", ...ALL_TOOLS.word },
  { id: "excel", ...ALL_TOOLS.excel },
  { id: "image", ...ALL_TOOLS.image },
]

export const getTotalToolCount = () => {
  return Object.values(ALL_TOOLS).reduce((sum, category) => sum + category.count, 0)
}

export const getAllTools = () => {
  return Object.values(ALL_TOOLS).flatMap(category =>
    category.tools.map(tool => ({ ...tool, category: category.name }))
  )
}

export const getToolById = (id: string) => {
  return getAllTools().find((tool) => tool.id === id)
}
